name: Deploy Dev

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  app-tests:
    uses: ./.github/workflows/app-tests.yml

  e2e-tests:
    uses: ./.github/workflows/e2e-tests.yml

  deploy:
    needs: [app-tests, e2e-tests]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment-name: dev
      azure-environment-name: dev
    secrets: inherit
