name: Deploy Stage

on:
  workflow_dispatch:
    inputs:
      deploy-ref:
        description: Git ref to deploy to stage
        required: false
        default: main

jobs:
  app-tests:
    uses: ./.github/workflows/app-tests.yml
    with:
      test-ref: ${{ inputs.deploy-ref }}

  e2e-tests:
    uses: ./.github/workflows/e2e-tests.yml
    with:
      test-ref: ${{ inputs.deploy-ref }}

  deploy:
    needs: [app-tests, e2e-tests]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment-name: stage
      azure-environment-name: stage
      deploy-ref: ${{ inputs.deploy-ref }}
    secrets: inherit
